    name: Deploy MultiDocker
    on:
      push:
        branches:
          - master # check your repo, your default branch might be master!
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t thiagomartins00/react-test -f ./client/Dockerfile.dev ./client
          - run: docker run -e CI=true thiagomartins00/react-test npm test
     
          - run: docker build -t thiagomartins00/multi-client-10-14 ./client
          - run: docker build -t thiagomartins00/multi-nginx-10-14 ./nginx
          - run: docker build -t thiagomartins00/multi-server-10-14 ./server
          - run: docker build -t thiagomartins00/multi-worker-10-14 ./worker
     
          - run: docker push thiagomartins00/multi-client-10-14
          - run: docker push thiagomartins00/multi-nginx-10-14
          - run: docker push thiagomartins00/multi-server-10-14
          - run: docker push thiagomartins00/multi-worker-10-14
    